Импорт библеотеки 


In [1]:
import numpy as np

Создать массви начало 0 коней 10 шаг 1


In [2]:
matrix = np.arange(0, 10, 1)

In [3]:
matrix

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Cоздать массив начало 1 конец 20 шаг 2 


In [4]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Нулевой массви из 12 чисел 


In [5]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Единичный массив 5х4

In [8]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Равномернораспредленный из 5, по отрезку 3 и 7

In [10]:
np.linspace(3, 7, 5)

array([3., 4., 5., 6., 7.])

Создать список из 9 распределенных чисел отрезка [3:7] и запихгуть в массив 3х3 

In [14]:
matrix = np.linspace(3,7, 9).reshape(3, 3)
matrix

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

Cоздать список из 10 рандомных чисел от 1 до 100

In [15]:
matrix = np.random.randint(1, 100, 10)

In [16]:
matrix

array([40, 43, 86, 55, 70, 29, 89, 41, 15, 81])

Выбрать максимальное их списка

In [20]:
martix_number = np.max(matrix)

In [22]:
martix_number

89

Cоздать список из 10 рандомных чисел от 1 до 20

In [24]:
matrix = np.random.randint(1, 20, 10)
matrix

array([ 9,  4, 17, 17, 18, 17, 16, 12,  6, 16])

Выаолнить срез массива от 1-го элемента до 6-го не включительно

In [28]:
matrix_a = matrix[1:6]
matrix_a

array([ 4, 17, 17, 18, 17])

Создайте двумерный массив, состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца.

In [33]:
matrix = np.random.randint(3, 11, 12).reshape(4,3)
matrix 

array([[ 5,  5, 10],
       [ 5,  9,  6],
       [ 8,  8,  4],
       [ 9,  3,  6]])

Создаем матрици а из исходно путем среза 

In [40]:
matrix_a = matrix[1:3 , :2]
print(matrix)
print(matrix_a)

[[ 5  5 10]
 [ 5  9  6]
 [ 8  8  4]
 [ 9  3  6]]
[[5 9]
 [8 8]]


создаем массив, ипользуя случаные значения от 0 до 9 не включительно, и запихиваем с матрицу 4х6

In [41]:
matrix = np.random.randint(0, 9, 24).reshape(4, 6)
matrix 

array([[6, 6, 7, 1, 0, 1],
       [4, 8, 2, 4, 3, 3],
       [0, 4, 5, 3, 4, 0],
       [3, 8, 6, 5, 0, 2]])

Создаем список А из слаженного массива используя списочные вырожения 

In [46]:
matrix_a = [i for i in matrix.flatten() if i > 3]
print(matrix)
print(matrix_a)

[[6 6 7 1 0 1]
 [4 8 2 4 3 3]
 [0 4 5 3 4 0]
 [3 8 6 5 0 2]]
[6, 6, 7, 4, 8, 4, 4, 5, 4, 8, 6, 5]


Создаем маасив, ипользуя случаные значения от 0 до 20 не включительно

In [53]:
matrix = np.random.randint(0, 9, 10)
print(matrix)

[6 4 1 2 3 1 4 5 8 1]


Cоздайте массив, состоящий из 10 элементов, начиная с 2

In [54]:
matrix_a = np.arange(2, 12)
print(matrix_a)

[ 2  3  4  5  6  7  8  9 10 11]


Сумма этих маассивов 

In [55]:
print(matrix + matrix_a)

[ 8  7  5  7  9  8 12 14 18 12]


Массив, состоящий из 7 случайных целых чисел из диапазона от 0 до 9

In [57]:
matrix = np.random.randint(0, 9, 7)
print(matrix)

[3 4 6 8 4 7 2]


Создайте новый массив, состоящий из 7 элементов первого массива, увеличенных в 3 раза

In [58]:
matrix3 = matrix * 3
print(matrix3)

[ 9 12 18 24 12 21  6]


Создайте массив, состоящий из квадратных корней 20 элементов по порядку, начиная с 7

In [63]:
matrix = np.sqrt(np.arange(7,27))
print(matrix)

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]


Произведение матриц x * y и y * x

In [68]:
x = np.array([1,2])
y = np.array([[4, 1], [2, 2]])
x @ y

array([8, 5])

In [70]:
y @ x

array([6, 6])

In [71]:
x = np.array([[1, 0], 
              [0, 1]])

y = np.array([[4, 1], 
              [2, 2], 
              [1, 1]])

In [73]:
y @ x

array([[4, 1],
       [2, 2],
       [1, 1]])

Массив, состоящий из 10 случайных целых чисел из диапазона от 0 до 9

In [75]:
matrix = np.random.randint(0, 9, 10)
print(matrix)

[5 1 5 8 4 3 5 2 8 4]


 Если элемент x меньше 3, замените его на 3. И если элемент x больше 7, замените его на 7.

In [90]:
matrix_a = np.arange(0, 10)
for i in range(0, 10):
    if matrix[i] < 3: 
        matrix_a[i] = 3
    elif matrix[i] > 7:
        matrix_a[i] = 7
    else:
        matrix_a[i] = matrix[i]
print(matrix_a)

[5 3 5 7 4 3 5 3 7 4]


Создайте массив

In [91]:
x = np.array([1, 3, 0, -1, -3])

Вычислите поэлементно знак x (sign x).

In [93]:
np.sign(x)

array([ 1,  1,  0, -1, -1])

Дана матрица

In [123]:
M = np.array([[0, 5, 9, 8, 2], 
              [3, 7, 4, 1, 6]])
np.max(M, axis=1)

array([9, 7])

In [124]:
np.argmax(M, axis=1)

array([2, 1], dtype=int64)

In [125]:
np.min(M, axis=1)

array([0, 1])

In [129]:
np.argmin(M, axis=1)

array([0, 3], dtype=int64)

In [126]:
np.max(M, axis=0)

array([3, 7, 9, 8, 6])

In [127]:
np.argmax(M, axis=0)

array([1, 1, 0, 0, 1], dtype=int64)

In [128]:
np.min(M, axis=0)

array([0, 5, 4, 1, 2])

In [131]:
np.argmin(M, axis=0)

array([0, 0, 1, 1, 0], dtype=int64)

In [135]:
matrix = np.arange(1, 10).reshape(3, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
print(np.mean(matrix))
print(np.median(matrix))
print(np.std(matrix))
print(np.var(matrix))

5.0
5.0
2.581988897471611
6.666666666666667
